stages:
- test
- build
- deploy

variables:
  DOCKER_DRIVER: overlay

test:
  stage: test
  image: node
  script:
  - npm i
  - npm test

docker-image:
  stage: build
  only:
  - master
  image: docker:git
  services:
  - docker:dind
  tags:
  - fast
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.cirici.com
  - docker build -t registry.cirici.com/alvarium/services/switchboardoperator/api .
  - docker push registry.cirici.com/alvarium/services/switchboardoperator/api

deploy:
  stage: deploy
  only:
  - master
  image: registry.cirici.com/alvarium/infrastructure/ansible-runner
  script:
  - ansible-playbook -i hosts deploy.yml
